language: python
services:
- docker
python:
- '3.6'
before_script:
- docker-compose build
- docker-compose run --rm web bash -c "python postgres_ready.py"
script:
- docker-compose run --rm web bash -c "./manage.py test"
after_success:
- docker login --username=_ --password="$HEROKU_AUTH_TOKEN" registry.heroku.com
- docker tag web registry.heroku.com/service-nom/web
- docker push registry.heroku.com/service-nom/web
notifications:
  email: true
cache:
  pip: true
env:
  global:
    secure: MwtcfSBXUHGnOjNpoqxdppBWlOLHTWjxVnaYBGhzI5RaSgg46833cp8J7ypiNQ6lAM5jJbMtgXljBlCXTWJVAriC3YjOheEJ134Vzxk26fLPKSpgNjRbgMTY67ppWMJMH//+H9UNBJjkZ8Bid/cRqT2Wi+xzy8xfdsJAODlsNnk8PqQz+1Q9+ElbHlEYdN0fHp95OAMfRYl5YmFG3daExwub8A0lfRr1uh5AeAy0XqNpjBlFArG78R9GtHUdYaJ5Ts/9Ox0AEbxlezkmrzFrPZkYzES6vFuXbb3Hnda35phsJfKhBz0OVBxcjXXeAw+MPYfy7Vyebfyrv0x6m8PkZaVjhOL7PLKqdkMWXOtSViNuniAQM/JLuMeFKXBXSwFu9tyrt4fXxkMQeaBORKEWh5sRRmc++YRpeuyi8Y8yftEMzh96jbcuTZwIiMOJkN6vHsaK+DL7qeKAGQBiINwHeLwqBTSPWU0mp3IDk1pOcYYYoJWkO3ytn5lsRDT5cxojmlMdRjYD9BZwr/g3KHCWmPXV4TfW+f9TLLF7nTYAaK7unOR2QGyR5oeyTVHSNQyh/ny189vjRywdeDlvtG6Vm0Zz3SgjGNyjguSAXLBpzvqWk2QlboC9FmJP0CL7bjsxi3pthB0Xmqq0LTQIJn0LToSBoTZNSRcbIfhPfABpHLE=
